version: "3.1"
services:
  db:
    image: postgres:alpine
    container_name: pg_web
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_DB: "${PG_DB}"
      POSTGRES_PASSWORD: "${PG_PASS}"
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - 5432:5432
  # server_main:
  #   build:
  #     context: .
  #     dockerfile: "Dockerfile"
  #   container_name: node_web
  #   ports:
  #     - "5000:5000"
