version: "2"
services:
  db:
    image: bitnami/postgresql
    container_name: pg_web
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_DB: "${PG_DB}"
      POSTGRES_PASSWORD: "${PG_PASS}"
    volumes:
      - postgresql_data/bitnami/postgresql
    ports:
      - 5432:5432

volumes:
  postgresql_data:
    driver: local
